### PR TITLE
move retrieving of secret key to testable function and test it

### PR DESCRIPTION
**Pull request by tobias47n9e**
The function that retrieves the SECRET_KEY from the environment is moved into a testable function. The function tries to get the key and raises and exception if the corresponding value (the SECRET_KEY) is not found (i.e. None), or the environement is not set up correctly. The conjugated test passes a wrong key to the function and checks if the right exception is raised.

### CODE REVIEW

**Comment by tobias47n9e** [comment]
Coverage does not seem to pick up that I am testing the exception. Odd. Will have to look into that tomorrow.

**Comment by coolharsh55** [comment]
@tobias47n9e the function you wrote has the same use case as the getenv function in Settings.py 
Django will complaint about missing secret key if it is not found, or is None

**Comment by tobias47n9e** [comment]
The function is just there, so we can test that part of the code. The test makes sure that Django does not launch without a secret key (It anyway does, but now we also test for it). But I might have misunderstood your comment.

**Comment by SanketDG** [comment]
@tobias47n9e You should just use `os.environ.get('SECRET_KEY')` as @coolharsh55 pointed out in #17. Its much more idiomatic.

So you would do like:

``` python
import os

def get_env_variable(key):
    return os.environ.get(key)

SECRET_KEY = get_env_variable('SECRET_KEY')
```

Then in the test:

``` python
def test_secret_key_missing():
    with pytest.raises(ImproperlyConfigured) as exc_info:
        settings.get_env_variable("non_existing_variable")
    assert str(exc_info.value) == "The SECRET_KEY setting must not be empty."
```

I am not sure that this should be tested.

**Comment by tobias47n9e** [comment]
I am going to close this PR, because testing for the missing key is not that essential.

**Pull request closed without merging**
